// Automatically generated by the bundler tool from c:\Documents and Settings\Xboxdev\Desktop\Xbox\Input\Gamepad\font12.rdf

#define font12_NUM_RESOURCES 2UL

#define font12_Font_OFFSET 0UL
#define font12_FontData_OFFSET 20UL
